[package]
name = "wfcnew"
version = "0.1.0"
authors = ["Ashley Ruglys <ashley.ruglys@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wfc = "0.9.1"
image = "0.23.9"
direction = "0.17.10"
rand = "0.7.3"
